services:
  - type: worker
    env: node
    name: supabase-to-loops
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: LOOPS_API_KEY
        sync: false